### ISSUE TITLE
Connection retryer

### ISSUE THREAD

**Issue by nnam** [auth0/passport-windowsauth#11]
When my domain controller reboots or is unavailable, this doesn't seem to retry the connection?  What do you think about adding a retry function?

**Comment by mweibel** [comment]
If you get a ECONNRESET or similar (didn't try other cases), add `reconnect: true` to the ldap options you pass. 
e.g. from the example:
```
passport.use(new WindowsStrategy({
  ldap: {
    url:             'ldap://wellscordoba.wellscordobabank.com/DC=wellscordobabank,DC=com',
    base:            'DC=wellscordobabank,DC=com',
    bindDN:          'someAccount',
    bindCredentials: 'andItsPass',
    reconnect: true // <----------------
  }
}, function(profile, done){
  User.findOrCreate({ waId: profile.id }, function (err, user) {
    done(err, user);
  });
}));
```

**Comment by kgurjit** [comment]
After my app is up for sometime, I see the following error: 
LDAP connection error: { Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:564:26)
---------------------------------------------

After I see this all calls to the following hang: passport.authenticate('WindowsAuthentication'

I added reconnect: true but it didn't help. I still see the same behavior. Can you please help?

**Comment by mweibel** [comment]
After adding `reconnect: true` it got better in my case, but I still can't login after some time. I'm trying to investigate that but not sure if I reach to some conclusion ;)

**Comment by MichaelMarkieta** [comment]
I left for the weekend and my site went down because of an uncaught ECONNRESET error so I will be testing the `reconnect: true` as well so I will report back too. I recommend adding all of the available options to the README, splitting them up between required and optional.

**Comment by mweibel** [comment]
After adding `reconnect: true` and my PR #45 got merged, I didn't have problems anymore. I suggest for you all to upgrade to the latest version and add the reconnect flag.

**Comment by cjmyles** [comment]
Would be great if an alternative LDAP url could be provided if the retry didn't work a second time
