### ISSUE TITLE
need to update passport

### ISSUE THREAD

**Issue by holdfenytolvaj** [auth0/passport-windowsauth#38]
There is a bug in passport, that is fixed with 2.2.
if the _passport.session is not set there is an exception at self._passport.session.user = obj;
Can it be updated?

**Comment by HNA-JP** [comment]
It's 2025 and this is still an issue because passport-windowsauth uses passport v0.1.15 whereas the production passport is, at the time of writing, v0.7.0.

passport repo issue regarding changes in session and serialization:
https://github.com/jaredhanson/passport/issues/939#issuecomment-1590046047

I see the following when trying to serialize the session:
```
TypeError: Cannot set properties of undefined (setting 'user')
    at /usr/local/app/node_modules/passport-windowsauth/node_modules/passport/lib/passport/http/request.js:45:35
    at pass (/usr/local/app/node_modules/passport/lib/authenticator.js:292:43)
    at serialized (/usr/local/app/node_modules/passport/lib/authenticator.js:301:7)
    at /usr/local/app/middleware/passport.js:52:42
    at pass (/usr/local/app/node_modules/passport/lib/authenticator.js:309:9)
    at Authenticator.serializeUser (/usr/local/app/node_modules/passport/lib/authenticator.js:314:5)
    at req.login.req.logIn (/usr/local/app/node_modules/passport-windowsauth/node_modules/passport/lib/passport/http/request.js:43:29)
    at strategy.success (/usr/local/app/node_modules/passport/lib/middleware/authenticate.js:265:13)
    at verified (/usr/local/app/node_modules/passport-windowsauth/lib/strategy.js:137:10)
    at Strategy._verify (/usr/local/app/middleware/passport.js:47:5)
```

As noted by @holdfenytolvaj :
`/node_modules/passport-windowsauth/node_modules/passport/lib/passport/http/request.js` at 45:35 shows:
```js
self._passport.session.user = obj;
```

Logging `self` by manually putting `console.log(self)` at line 45 shows the following: 
```
...
<snipped for brevity> 
...
sessionID: '<express-session-id>',
session: Session {
  cookie: { path: '/', _expires: null, originalMaxAge: null, httpOnly: true }
},
logIn: [Function (anonymous)],
login: [Function (anonymous)],
logOut: [Function (anonymous)],
logout: [Function (anonymous)],
isAuthenticated: [Function (anonymous)],
isUnauthenticated: [Function (anonymous)],
_sessionManager: SessionManager {
  _key: 'passport',
  _serializeUser: [Function: bound ]
},
_passport: {
  instance: Authenticator {
    _key: 'passport',
    _strategies: [Object],
    _serializers: [Array],
    _deserializers: [Array],
    _infoTransformers: [],
    _framework: [Object],
    _sm: [SessionManager],
    Authenticator: [Function: Authenticator],
    Passport: [Function: Authenticator],
    Strategy: [Function],
    strategies: [Object],
    _userProperty: 'user'
  }
},
...
<snipped for brevity> 
...
user: { // custom user model derived from AD/LDAP
  name: '<name>',
  employeeID: '<employeeID>',
  email: '<email>',
  username: '<username>',
  upn: '<upn>',
  distinguishedName: '<dn>',
  manager: '<manager>'
},
...
<snipped for brevity> 
```

It's possible to add `session: false` in your `passport.authenticate()` strategy

Example:
```js
router.post('/login',
    (req, res, next) => { console.log(req.session); next() }, // shows passport's session doesn't exist yet
    passport.authenticate('WindowsAuthentication', {
        successRedirect: '/',
        failureRedirect: '/api/login',
        session: false,
        failureFlash:    false
    }),
);
```

But this will prevent sessions from being saved and will likely re-authenticate you on each request...

**Comment by HNA-JP** [comment]
Testing manually, it broke after passport `v0.5.0`

Unfortunately there's a known vulnerability that was patched in `v0.6.0` so downgrading isn't really an option
https://security.snyk.io/vuln/SNYK-JS-PASSPORT-2840631

Edit: Snyk actually automatically opened a PR about this: #68
