### ISSUE TITLE
Getting uncaught error in none-integrated mode after the connection reset

### ISSUE THREAD

**Issue by dkonasov** [auth0/passport-windowsauth#57]
From logs:
```
/node/node_modules/passport-windowsauth/lib/LdapLookup.js:24
    if (e.errno === 'ECONNRESET' && self._client.reconnect) return;
                                         ^

TypeError: Cannot read property '_client' of undefined
    at Client.<anonymous> (/node/node_modules/passport-windowsauth/lib/LdapLookup.js:24:42)
    at Client.emit (events.js:180:13)
    at Socket.onSocketError (/node/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
```

**Comment by dkonasov** [comment]
Created PR to fix this.
https://github.com/auth0/passport-windowsauth/pull/58
